play_media:
  description: Downloads file from given url.
  fields:
    entity_id:
      name: Entity
      description: Name of entity to send command.
      required: true
      selector:
        entity:
          domain: media_player
    media_content_id:
      description: The ID of the content to play. Platform dependent.
      example: 'https://soundcloud.com/bruttoband/brutto-11'
    media_content_type:
      description: The type of the content to play. Must be one of MUSIC, TVSHOW, VIDEO, EPISODE, CHANNEL or PLAYLIST MUSIC.
      example: 'music'
      
